# beep health status
print("Please enter the number of lives.")
lives = int(input())
print()
print("Please enter the energy level.")
energy = int(input())
print()
print("Please enter shield level.")
shield = int(input())
print()
print("Health has been set.")
print()
print("Lives: ", "♥" * lives)
print("Energy: ", "♦" * energy)
print("Shield: ", "♦" * shield)